# version: "3.9"
name: investron_dev_env
services:
  app:
    build:
      context: .
      target: backend
    container_name: investron-app  
    restart: unless-stopped  
    expose:
      - 9000
    env_file: ./.env.docker
    environment:
      APP_ENV: local
      APP_DEBUG: true   
      DB_CONNECTION: mysql   
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: investron_db
      DB_USERNAME: investron_user
      DB_PASSWORD: secret_password    
    develop:
      watch: 
        - action: sync
          path: ./
          target: /var/www/html  
          ignore:
            - vendor/**
            - node_modules/**
            - storage/**
            - public/build/**
        - action: rebuild
          path: composer.json    
    depends_on:
      - db
    networks:
      - investron_net    

  nginx:
    build: 
      context: .
      target: webserver
    container_name: investron-web   
    restart: unless-stopped 
    ports:
      - "5000:80"   
    depends_on:
      - app
    networks:
      - investron_net

  db:
    image: mysql:8.0
    container_name: investron-db    
    environment:
      MYSQL_DATABASE: investron_db
      MYSQL_USER: investron_user
      MYSQL_PASSWORD: secret_password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - investron_net

  adminer:
    image: adminer
    container_name: investron-adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - investron_net

volumes:
  mysql_data:    

networks:
  investron_net:
    driver: bridge