user nginx;
worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65s;

    server{
        listen 80;
        server_name localhost;
        root /var/www/html/public;
        index index.php index.html index.htm;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            fastcgi_pass app:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;            
            fastcgi_param PATH_INFO $fastcgi_path_info;
            include fastcgi_params;
            include fastcgi.conf;

            fastcgi_hide_header X-Powered-By;
            add_header X-Frame-Options "SAMEORIGIN" always;
            add_header X-XSS-Content-Options "1; mode=block" always;            
        }

        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-XSS-Content-Options "1; mode=block" always;
        add_header X-Content-Type-Options "nosniff" always;
       
    }
}